- name: Install nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Include common role
  ansible.builtin.include_role:
    name: common
    tasks_from: download

- name: Start nginx service
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes






  # mv frontend-main/localhost.conf /etc/nginx/default.d/roboshop.conf
    # systemctl enable nginx
    # systemctl restart nginx