- name: Install nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Include common role
  ansible.builtin.include_role:
    name: common
    tasks_from: download

#- name: Update systemd config
#  ansible.builtin.template:
#    src: localhost.conf
#    dest: /etc/nginx/default.d/roboshop.conf

- name: Copy Nginx Configuration
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Start nginx service
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes





