- name: Fail if MYSQL_PASSWORD does not exist
  ansible.builtin.fail:
    msg: MYSQL_PASSWORD is missing
  when: MYSQL_PASSWORD is undefined

- name: Configure yum repos
  ansible.builtin.template:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Install mysql database
  ansible.builtin.yum:
    name:
      - mysql-community-server
      - python36-PyMySQL
    state: installed

- name: Start mysql sever
  ansible.builtin.systemd:
    name: mysqld
    state: started
    enabled: yes

- name: Read the mysql content
  ansible.builtin.slurp:
    src: /var/log/mysqld.log
  register: mysql_log

- name: Print mysql DEFAULT_PASSWORD
  ansible.builtin.set_fact:
    DEFAULT_PASSWORD: "{{ mysql_log['content'] | b64decode | regex_search('.*temporary password.*') | split(' ') | last }}"

- name: Check MYSQL_PASSWORD rest or not
  community.mysql.mysql_info:
    login_user: root
    login_password: "{{MYSQL_PASSWORD}}"
    filter: version
#  ignore_errors: yes
#  register: mysql_conn
#
#- name: Reset MYSQL_PASSWORD
#  ansible.builtin.shell: echo "ALTER USER 'root'@'localhost' IDENTIFIED BY '{{MYSQL_PASSWORD}}';" | mysql --connect-expired-password  -uroot -p"{{DEFAULT_PASSWORD}}"
#  when: mysql_conn is failed
#
#- name: check mysql validate_password plugin
#  ansible.builtin.shell: echo show plugins | mysql -uroot -p"{{MYSQL_PASSWORD}}" | grep validate_password
#  register: plugin_info
#  ignore_errors: yes
#
#- name: remove mysql validate_password plugin
#  ansible.builtin.shell: echo "uninstall plugin validate_password;" | mysql -uroot -p"{{MYSQL_PASSWORD}}"
#  when: plugin_info is succeeded
#
#- name: Download and Extract {{ COMPONENT }} content
#  ansible.builtin.unarchive:
#    src: https://github.com/roboshop-devops-project/{{ COMPONENT }}/archive/main.zip
#    dest: /tmp
#    remote_src: yes
#
#- name: Load Schema
#  community.mysql.mysql_db:
#    name: all
#    state: import
#    target: /tmp/mysql-main/shipping.sql
#    login_user: root
#    login_password: "{{MYSQL_PASSWORD}}"





    # cd mysql-main
    # mysql -u root -pRoboShop@1 <shipping.sql
    