- name: Add application user
  ansible.builtin.user:
    name: roboshop
  register: app_user

- name: Remove app location
  ansible.builtin.file:
    path: "{{ APP_LOCATION }}"
    state: absent

- name: add app location
  ansible.builtin.file:
    path: "{{ APP_LOCATION }}"
    state: directory

#- name: Download and Extract {{ COMPONENT }} content
#  ansible.builtin.unarchive:
#    src: https://github.com/roboshop-devops-project/{{ COMPONENT }}/archive/main.zip
#    dest: /tmp
#    remote_src: yes
#
#- name: copy {{ COMPONENT }}
#  ansible.builtin.copy:
#    src: /tmp/{{ COMPONENT }}-main/{{SUFFIX}}
#    dest: "{{ APP_LOCATION }}/"
#    remote_src: yes

- name: Get the latest version of nexus artifact of {{ COMPONENT }} component
  ansible.builtin.shell: curl -s http://nexus.roboshop.internal:8081/service/rest/repository/browse/frontend/ | grep zip | sed -e 's/"/ /g' | xargs -n1 | grep ^http | tail -n1
  register: out
  when: APP_VERSION is not defined

- name: Declare url fact for latest version
  ansible.builtin.set_fact:
    URL: "{{out.stout}}"
  when: APP_VERSION is not defined

- name: Declare url fact
  ansible.builtin.set_fact:
    URL: http://nexus.roboshop.internal:8081/repository/{{ COMPONENT }}/{{ COMPONENT }}-{{APP_VERSION}}.zip
  when: APP_VERSION is defined

- name: Download and Extract {{ COMPONENT }} content from nexus
  ansible.builtin.unarchive:
    src: "{{URL}}"
    dest: "{{ APP_LOCATION }}"
    remote_src: yes