- name: Set Host-name
  ansible.builtin.shell: set-hostname {{ COMPONENT }}

- name: Install pip-3 dependencies for aws secrets
  ansible.builtin.pip:
    name:
      - botocore
      - boto3
    executable: pip3