- name: Configure yum repos
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: Install nodejs
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: Include common role
  ansible.builtin.include_role:
    name: common
    tasks_from: download


#$ npm install

#1. Update SystemD file with correct IP addresses
#
#Update `MONGO_DNSNAME` with MongoDB Server IP


  # mv /home/roboshop/catalogue/systemd.service /etc/systemd/system/catalogue.service
  # systemctl daemon-reload
  # systemctl start catalogue
  # systemctl enable catalogue
